from environs import Env

env = Env()
env.read_env()

DICT_ENVS = {}

DICT_ENVS["SECRET_KEY"] = env.str("SECRET_KEY")

DICT_ENVS["TEST"] = env.bool("TEST")

if not env.bool("TEST"):
    DICT_ENVS["LOGSTASH_HOST"] = env.str("LOGSTASH_HOST")
    DICT_ENVS["LOGSTASH_PORT"] = env.int("LOGSTASH_PORT")

    DICT_ENVS["CONSUL_HOST"] = env.str("CONSUL_HOST", None)
    DICT_ENVS["CONSUL_PORT"] = env.int("CONSUL_PORT", None)
    DICT_ENVS["CONSUL_TOKEN"] = env.str("CONSUL_TOKEN", None)

DICT_ENVS["GATEWAY_TIMEOUT"] = env.int("GATEWAY_TIMEOUT", 59)

DICT_ENVS["FASTAPI_IP"] = env.str("FASTAPI_IP")
DICT_ENVS["FASTAPI_PORT"] = env.int("FASTAPI_PORT")

DICT_ENVS["POSTGRES_HOST"] = env.str("POSTGRES_HOST")
DICT_ENVS["POSTGRES_PORT"] = env.int("POSTGRES_PORT")
DICT_ENVS["POSTGRES_DB"] = env.str("POSTGRES_DB")
DICT_ENVS["POSTGRES_USER"] = env.str("POSTGRES_USER")
DICT_ENVS["POSTGRES_PASSWORD"] = env.str("POSTGRES_PASSWORD")
