version: '3.1'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./scheme.sql:/docker-entrypoint-initdb.d/scheme.sql
    networks:
      - user_service_network

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${FASTAPI_PORT}:${FASTAPI_PORT}"
    env_file: .env
    networks:
      - user_service_network

networks:
  user_service_network: